//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministrationApp_SPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuildingType
    {
        public BuildingType()
        {
            this.Buildings = new HashSet<Buildings>();
        }
    
        public int BuildingTypeID { get; set; }
        public string TypeName { get; set; }
        public string TypeDescription { get; set; }
    
        public virtual ICollection<Buildings> Buildings { get; set; }
    }
}
