//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministrationApp_SPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuildingsView
    {
        public int BuildingID { get; set; }
        public string BuildingName { get; set; }
        public Nullable<int> BuildingNumber { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string StreetName { get; set; }
        public Nullable<int> StreetNumber { get; set; }
        public Nullable<decimal> PostCodeNumber { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string TypeName { get; set; }
    }
}
