//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministrationApp_SPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItemsView
    {
        public int MenuItemID { get; set; }
        public string MenuItemText { get; set; }
        public string MenuItemType { get; set; }
        public string MenuItemDescription { get; set; }
        public int ApplicationMenuID { get; set; }
        public string Name { get; set; }
        public string GlyphCode { get; set; }
        public Nullable<bool> IsForAdminUse { get; set; }
        public Nullable<int> Sort { get; set; }
    }
}
