//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministrationApp_SPP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class UserBuildingView
    {
        [Key]
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string LoginName { get; set; }
        public string EmailAddress { get; set; }
        public string BuildingName { get; set; }
        public string StreetName { get; set; }
        public Nullable<int> StreetNumber { get; set; }
        public Nullable<decimal> PostCodeNumber { get; set; }
        public Nullable<bool> IsAdministrator { get; set; }
    }
}
